//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БОРИСОВ_ТЕКСТИЛЬ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class БОРИСОВ_ТЕКСТИЛЬEntities : DbContext
    {
        private static БОРИСОВ_ТЕКСТИЛЬEntities _context;
        public БОРИСОВ_ТЕКСТИЛЬEntities()
            : base("name=БОРИСОВ_ТЕКСТИЛЬEntities")
        {
        }
        public static БОРИСОВ_ТЕКСТИЛЬEntities GetContext()
        {
            if (_context == null)
                _context = new БОРИСОВ_ТЕКСТИЛЬEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Корзина> Корзина { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Состав_Заказа> Состав_Заказа { get; set; }
        public virtual DbSet<Страна_Производитель> Страна_Производитель { get; set; }
        public virtual DbSet<Тип_Пользователя> Тип_Пользователя { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
